/*
 * Node.cpp
 *
 * /TheCompilerFramework/Sources/src/Node.cpp
 *
 *       Author: Mihir Kasmalkar
 * Date created: Aug 29, 2015
 *
 *      Purpose: Represents a branch or leaf on the AST. A node wraps a token, and can contain other tokens.
 *
 *        Usage: Will be generated by the Parser's astAction methods. The Parser will then add the Nodes
 *               to the AST.
 *
 *        Notes:
 *
 */

#include <iostream>

#include "Node.hpp"

namespace node
{
    Node::Node(token::Token token, NodeType type, std::shared_ptr<Branchable> root) :
        Branchable(root), token(token), type(type)
    {

    }

    Node::~Node()
    {

    }

    void Node::add(std::shared_ptr<Node> n)
    {
        nodes.push_back(n);
    }

    std::shared_ptr<node::Node> Node::getNode(unsigned int index)
    {
        if (index >= 0 && index < nodes.size()) {
            return nodes.at(index);
        }

        return std::shared_ptr<node::Node> { };
    }

    void Node::print(std::string tabs)
    {
        std::cout << tabs << "Node: " << token.getText() << "\n"
                  << tabs << "\tType: " << type
                  << "\n";
    }

} /* namespace node */
